### ISSUE TITLE
Zenon does not compile with recent versions of Coq

### ISSUE THREAD

**Issue by rafoo** [zenon-prover/zenon#1]
Errors are thrown when attempting to compile Zenon with Coq 8.11; the `Implicit Arguments` vernacular command is now simply called `Arguments`.

Possible fixes:
- fix the opam file to require an old-enough version of Coq (I haven't looked at the Coq changelog yet to find which version introduced the syntax change)
- remove the "Implicit" part of the command in the Coq files and require a recent-enough version of Coq
- stop relying on implicit arguments; removing all implicit argument declarations pass Coq checking but I don't know if it breaks the generated proofs or the tools using the Zenon Coq Library such as FoCaLiZe.

**Comment by rafoo** [comment]
I have just looked at the Coq changelog in https://coq.github.io/doc/V8.11.1/refman/changes.html, the change in the syntax of `Implicit Arguments` comes from Coq v8.9:
> Removed deprecated commands Arguments Scope and Implicit Arguments in favor of Arguments (scopes) and Arguments (implicits), with the help of Jasper Hugunin.

**Comment by rafoo** [comment]
The opam package in https://github.com/ocaml/opam-repository/blob/master/packages/zenon/zenon.0.8.4/opam already declares an optional dependency to Coq v<8.9, I think it should be replaced by a conflict with Coq v>=8.9.

**Comment by damiendoligez** [comment]
Fixed in release 0.8.5, which will soon be in opam (https://github.com/ocaml/opam-repository/pull/17480)

**Comment by rafoo** [comment]
Thank you!


-------- Courriel d’origine --------
De : Damien Doligez <notifications@github.com>
Envoyé : 23 octobre 2020 17:42:26 GMT+02:00
À : zenon-prover/zenon <zenon@noreply.github.com>
Cc : "Raphaël Cauderlier" <cauderlier@crans.org>, Author <author@noreply.github.com>
Objet : Re: [zenon-prover/zenon] Zenon does not compile with recent versions of Coq (#1)

Closed #1.


-- 
Raphaël Cauderlier
